name: demucs

channels:
  - pytorch
  - conda-forge

dependencies:
  - python>=3.7,<3.9
  - ffmpeg>=4.2
  - pytorch>=1.8.1
  - cudatoolkit>=10
  - torchaudio>=0.8
  - tqdm>=4.36
  - pip
  - pip:
    - dora-search
    - diffq>=0.2.0
    - julius>=0.2.3
    - lameenc>=1.2
    - musdb>=0.4.0
    - museval>=0.4.0
    - soundfile
    - treetable>=0.2.3
